version: '3.4'

services:
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - users_app:/app
      - users_gem_cache:/usr/local/bundle/gems

  articles:
    build:
      context: ./articles
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - articles_app:/app
      - articles_gem_cache:/usr/local/bundle/gems

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - articles
      - users
    volumes:
      - gateway:/app
    environment:
      USERS_HOST: users:3000
      ARTICLES_HOST: articles:3000

volumes:
  users_app:
  users_gem_cache:
  articles_app:
  articles_gem_cache:
  gateway:
