subgraphs:
  users:
    routing_url: http://localhost:3000/graphql
    schema:
      subgraph_url: http://localhost:3000/graphql
  articles:
    routing_url: http://localhost:3001/graphql
    schema:
      subgraph_url: http://localhost:3001/graphql
