subgraphs:
  users:
    routing_url: http://${USERS_HOST}:3000/graphql
    schema:
      subgraph_url: http://${USERS_HOST}:3000/graphql
  articles:
    routing_url: http://${ARTICLES_HOST}:3000/graphql
    schema:
      subgraph_url: http://${ARTICLES_HOST}:3000/graphql
